CREATE TABLE ACCOUNT (
    ACCOUNT_NUMBER VARCHAR(100) NOT NULL,
    HASH_VALUE VARCHAR(255),
    TYPE VARCHAR(100),
    ROUND_TRIPS INT,
    IS_DAY_TRADER BOOLEAN,
    IS_CLOSING_ONLY_RESTRICTED BOOLEAN,
    PFCB_FLAG BOOLEAN,
    PRIMARY KEY (ACCOUNT_NUMBER)
);