CREATE TABLE ACCOUNT_REFERENCE (
    ACCOUNT_NUMBER VARCHAR(100) NOT NULL,
	ACCOUNT_DESCRIPTION VARCHAR(100),
    PRIMARY KEY (ACCOUNT_NUMBER)
);

INSERT INTO ACCOUNT_REFERENCE (ACCOUNT_NUMBER, ACCOUNT_DESCRIPTION)
VALUES ('34031648', "Dario's Brokerage Account");

INSERT INTO ACCOUNT_REFERENCE (ACCOUNT_NUMBER, ACCOUNT_DESCRIPTION)
VALUES ('70587642', "Genalyn's Brokerage Account");

INSERT INTO ACCOUNT_REFERENCE (ACCOUNT_NUMBER, ACCOUNT_DESCRIPTION)
VALUES ('83562937', "Genalyn's IRA Account");

INSERT INTO ACCOUNT_REFERENCE (ACCOUNT_NUMBER, ACCOUNT_DESCRIPTION)
VALUES ('87633692', "Dario's IRA Account");

COMMIT;

select distinct(account_number) from ACCOUNT;

SELECT * FROM ACCOUNT_REFERENCE;