CREATE TABLE ACCOUNT (
    ACCOUNT_NUMBER VARCHAR(100) NOT NULL,
	RECORD_DATE DATE,
    HASH_VALUE VARCHAR(255),
    TYPE VARCHAR(100),
    ROUND_TRIPS INT,
    IS_DAY_TRADER BOOLEAN,
    IS_CLOSING_ONLY_RESTRICTED BOOLEAN,
    PFCB_FLAG BOOLEAN,
    AGG_BALANCE_CURRENT_LIQUIDATION_VALUE DECIMAL(12, 4),
    AGG_BALANCE_LIQUIDATION_VALUE DECIMAL(12, 4),
    PRIMARY KEY (ACCOUNT_NUMBER, RECORD_DATE)
);

SELECT * FROM ACCOUNT ORDER BY RECORD_DATE DESC;