CREATE TABLE CURRENT_BALANCE (
    ACCOUNT_NUMBER VARCHAR(100) NOT NULL,
    accruedInterest DECIMAL(12, 4),
    cashBalance DECIMAL(12, 4),
    cashReceipts DECIMAL(12, 4),
    longOptionMarketValue DECIMAL(12, 4),
    liquidationValue DECIMAL(12, 4),
    longMarketValue DECIMAL(12, 4),
    moneyMarketFund DECIMAL(12, 4),
    savings DECIMAL(12, 4),
    shortMarketValue DECIMAL(12, 4),
    pendingDeposits DECIMAL(12, 4),
    mutualFundValue DECIMAL(12, 4),
    bondValue DECIMAL(12, 4),
    shortOptionMarketValue DECIMAL(12, 4),
    availableFunds DECIMAL(12, 4),
    availableFundsNonMarginableTrade DECIMAL(12, 4),
    buyingPower DECIMAL(12, 4),
    buyingPowerNonMarginableTrade DECIMAL(12, 4),
    dayTradingBuyingPower DECIMAL(12, 4),
    equity DECIMAL(12, 4),
    equityPercentage DECIMAL(12, 4),
    longMarginValue DECIMAL(12, 4),
    maintenanceCall DECIMAL(12, 4),
    maintenanceRequirement DECIMAL(12, 4),
    marginBalance DECIMAL(12, 4),
    regTCall DECIMAL(12, 4),
    shortBalance DECIMAL(12, 4),
    shortMarginValue DECIMAL(12, 4),
    sma DECIMAL(12, 4)
);