/*
 * DDL FOR THE DAILY_BALANCE TABLE
 */
CREATE TABLE DAILY_BALANCE (
    ACCOUNT_NUMBER INT,
    RECORD_DATE DATE,
    LIQUIDITY_VALUE DECIMAL(10, 2),
    PRIMARY KEY (ACCOUNT_NUMBER, RECORD_DATE)
);

/*
 * QUERIES FOR THE DAILY_BALANCE TABLE
 */
SELECT * FROM DAILY_BALANCE;

SELECT * from DAILY_BALANCE WHERE date(RECORD_DATE) = CURDATE();

SELECT * FROM DAILY_BALANCE WHERE date(RECORD_DATE) = (SELECT max(RECORD_DATE) FROM DAILY_BALANCE);