USE financedb;

CREATE TABLE DASHBOARD (
    SYMBOL VARCHAR(100) NOT NULL,
    RECORD_DATE DATE,
    SENTIMENT VARCHAR(100) NOT NULL,
    RSI VARCHAR(100) NOT NULL,
    PRIMARY KEY (SYMBOL, RECORD_DATE)
);

SELECT * FROM DASHBOARD;