CREATE TABLE EXECUTION_LEGS (
    ACCOUNT_NUMBER VARCHAR(100) NOT NULL,
	ORDER_ID VARCHAR(100),    
    ACTIVITY_ID VARCHAR(100),
    LEG_ID INT,
    QUANTITY DECIMAL(12, 4),
    MISMARKED_QUANTITY DECIMAL(12, 4),
    PRICE DECIMAL(12, 4),
    RECORD_TIME DATETIME,
    INSTRUMENT_ID VARCHAR(100),
    PRIMARY KEY (ACCOUNT_NUMBER, ORDER_ID, ACTIVITY_ID, LEG_ID)
);