USE financedb;

CREATE INDEX datetime_index_spx_ohlc
ON SPX_OHLC_MINUTES (DATETIME);

CREATE INDEX datetime_index_ohlc
ON OHLC_MINUTES (DATETIME);

SELECT DATE(MAX(DATETIME)) FROM SPX_OHLC_MINUTES; # .0067 SECONDS

SELECT MAX(DATE(DATETIME)) FROM SPX_OHLC_MINUTES; # .567 SECONDS

SET @max_date_spx = (SELECT MAX(DATE(DATETIME)) FROM SPX_OHLC_MINUTES);
SET @max_date_ohlc = (SELECT MAX(DATE(DATETIME)) FROM OHLC_MINUTES);

SELECT TICKER, RECORD_DATE, COUNT FROM (
    SELECT 'SPX' AS TICKER, DATE(DATETIME) AS RECORD_DATE, COUNT(*) AS COUNT 
    FROM SPX_OHLC_MINUTES 
    WHERE DATE(DATETIME) = @max_date_spx
    GROUP BY RECORD_DATE
    UNION
    SELECT TICKER, DATE(DATETIME) AS RECORD_DATE, COUNT(*) AS COUNT 
    FROM OHLC_MINUTES 
    WHERE DATE(DATETIME) = @max_date_ohlc
    GROUP BY TICKER, RECORD_DATE
) AS A 
ORDER BY A.TICKER; # 3.212 SECONDS

/*
 * Query for the Home screnne (too slow)
 */
SELECT TICKER, RECORD_DATE, COUNT FROM (
SELECT 'SPX' AS TICKER, DATE(DATETIME) AS RECORD_DATE, COUNT(*) AS COUNT FROM SPX_OHLC_MINUTES 
WHERE DATE(DATETIME) = (SELECT MAX(DATE(DATETIME)) FROM SPX_OHLC_MINUTES) 
GROUP BY RECORD_DATE
UNION
SELECT TICKER, DATE(DATETIME) AS RECORD_DATE, COUNT(*) AS COUNT FROM OHLC_MINUTES 
WHERE DATE(DATETIME) = (SELECT MAX(DATE(DATETIME)) FROM OHLC_MINUTES) 
GROUP BY TICKER, RECORD_DATE)
AS A ORDER BY A.TICKER; # 4.067

SELECT TICKER, RECORD_DATE, COUNT FROM (
SELECT 'SPX' AS TICKER, DATE(DATETIME) AS RECORD_DATE, COUNT(*) AS COUNT FROM SPX_OHLC_MINUTES 
WHERE DATE(DATETIME) = (SELECT DATE(MAX(DATETIME)) FROM SPX_OHLC_MINUTES) 
GROUP BY RECORD_DATE
UNION
SELECT TICKER, DATE(DATETIME) AS RECORD_DATE, COUNT(*) AS COUNT FROM OHLC_MINUTES 
WHERE DATE(DATETIME) = (SELECT DATE(MAX(DATETIME)) FROM OHLC_MINUTES) 
GROUP BY TICKER, RECORD_DATE)
AS A ORDER BY A.TICKER; # 4.067



/*
 * Number of positions per account 
 */
SELECT 
	RECORD_DATE, 
    ACCOUNT_NUMBER, 
	COUNT(*) 
FROM 
	POSITION_VIEW
GROUP BY
	RECORD_DATE, ACCOUNT_NUMBER
ORDER BY RECORD_DATE DESC;

/*
 * Explore the data for option chain
 */

SELECT 
	*
FROM 
	OPTION_CHAIN_VIEW 
WHERE
	SYMBOL = '$SPX' AND
	RECORD_DATE = '2024-06-23' AND
    EXP_DATE_MAP LIKE '2024-07-23%' AND
    EXP_DATE_PRICE_MAP LIKE '5200%'; 

/* 
 * COUNT OF PUT AND CALL 
 */
SELECT 
	'PUT',
	COUNT(*)
FROM 
	OPTION_CHAIN_VIEW 
WHERE
	SYMBOL = '$SPX' AND
    PUT_CALL = 'PUT' AND
	RECORD_DATE = '2024-06-23' AND
    EXP_DATE_MAP = '2024-06-24:1'
UNION
SELECT 
	'CALL',
	COUNT(*)
FROM 
	OPTION_CHAIN_VIEW 
WHERE
	SYMBOL = '$SPX' AND
    PUT_CALL = 'CALL' AND
	RECORD_DATE = '2024-06-23' AND
    EXP_DATE_MAP = '2024-06-24:1'; 
