USE financedb;

/*
 * Number of positions per account 
 */
SELECT 
	RECORD_DATE, 
    ACCOUNT_NUMBER, 
	COUNT(*) 
FROM 
	POSITION_VIEW
GROUP BY
	RECORD_DATE, ACCOUNT_NUMBER
ORDER BY RECORD_DATE DESC;

/*
 * Explore the data for option chain
 */

SELECT 
	*
FROM 
	OPTION_CHAIN_VIEW 
WHERE
	SYMBOL = '$SPX' AND
	RECORD_DATE = '2024-06-23' AND
    EXP_DATE_MAP = '2024-06-24:1'; 

/* COUNT OF PUT AND CALL */
SELECT 
	'PUT',
	COUNT(*)
FROM 
	OPTION_CHAIN_VIEW 
WHERE
	SYMBOL = '$SPX' AND
    PUT_CALL = 'PUT' AND
	RECORD_DATE = '2024-06-23' AND
    EXP_DATE_MAP = '2024-06-24:1'
UNION
SELECT 
	'CALL',
	COUNT(*)
FROM 
	OPTION_CHAIN_VIEW 
WHERE
	SYMBOL = '$SPX' AND
    PUT_CALL = 'CALL' AND
	RECORD_DATE = '2024-06-23' AND
    EXP_DATE_MAP = '2024-06-24:1'; 
