CREATE TABLE INITIAL_BALANCE (
    ACCOUNT_NUMBER VARCHAR(100) NOT NULL,
    accruedInterest DECIMAL(12, 4),
    availableFundsNonMarginableTrade DECIMAL(12, 4),
    bondValue DECIMAL(12, 4),
    buyingPower DECIMAL(12, 4),
    cashBalance DECIMAL(12, 4),
    cashAvailableForTrading DECIMAL(12, 4),    
    cashReceipts DECIMAL(12, 4),
    dayTradingBuyingPower DECIMAL(12, 4),
	dayTradingBuyingPowerCall DECIMAL(12, 4),
    dayTradingEquityCall DECIMAL(12, 4),
    equity DECIMAL(12, 4),
    equityPercentage DECIMAL(12, 4),
    liquidationValue DECIMAL(12, 4),
    longMarginValue DECIMAL(12, 4),
    longOptionMarketValue DECIMAL(12, 4),
    longStockValue DECIMAL(12, 4),
    maintenanceCall DECIMAL(12, 4),
    maintenanceRequirement DECIMAL(12, 4),
    margin DECIMAL(12, 4),
    marginEquity DECIMAL(12, 4),
    moneyMarketFund DECIMAL(12, 4),
    mutualFundValue DECIMAL(12, 4),
    regTCall DECIMAL(12, 4),
    shortMarginValue DECIMAL(12, 4),
    shortOptionMarketValue DECIMAL(12, 4),
    shortStockValue DECIMAL(12, 4),
    totalCash DECIMAL(12, 4),
    isInCall BOOLEAN,
    pendingDeposits DECIMAL(12, 4),
    marginBalance DECIMAL(12, 4),
    shortBalance DECIMAL(12, 4),
    accountValue DECIMAL(12, 4)
);