use financedb;

CREATE TABLE IF NOT EXISTS NEWS_SENTIMENT (
    SYMBOL VARCHAR(100) NOT NULL,
    RECORD_DATE DATE,
    GOOGLE_NEWS_HEADLINES VARCHAR(10000),
	OVERALL_SENTIMENT VARCHAR(100),
    PRIMARY KEY (SYMBOL, RECORD_DATE)
);

# ALTER TABLE NEWS_SENTIMENT DROP COLUMN VADER_SENTIMENT_RATING;

SELECT SYMBOL, GOOGLE_NEWS_HEADLINES, OVERALL_SENTIMENT FROM NEWS_SENTIMENT WHERE RECORD_DATE = (SELECT MAX(RECORD_DATE) FROM NEWS_SENTIMENT);

SELECT * FROM NEWS_SENTIMENT ORDER BY RECORD_DATE DESC;