use financedb;

CREATE TABLE OPTION_CHAIN (
    SYMBOL VARCHAR(100) NOT NULL,
	RECORD_DATE DATE,  
    
    STATUS VARCHAR(100),
    STRATEGY VARCHAR(100),
    INTERVAL_VALUE DECIMAL(12, 4),
    IS_DELAYED BOOLEAN,
    IS_INDEX BOOLEAN,
    INTEREST_RATE DECIMAL(12, 4),
    UNDERLYING_PRICE DECIMAL(12, 4),
    VOLATILITY DECIMAL(12, 4),
    DAYS_TO_EXPIRATION DECIMAL(12, 4),
    NUMBER_OF_CONTRACTS INT,
    ASSET_MAIN_TYPE VARCHAR(100),
    ASSET_SUB_TYPE VARCHAR(100),
    IS_CHAIN_TRUNCATED BOOLEAN,
    PRIMARY KEY (SYMBOL, RECORD_DATE)
);

SELECT * FROM OPTION_CHAIN;