CREATE OR REPLACE VIEW OPTION_CHAIN_VIEW AS
SELECT 
    OC.SYMBOL,
	OC.RECORD_DATE,      
    OC.STATUS,
    OC.STRATEGY,
    OC.INTERVAL_VALUE,
    OC.IS_DELAYED,
    OC.IS_INDEX,
    OC.INTEREST_RATE,
    OC.UNDERLYING_PRICE,
    OC.VOLATILITY,
    #OC.DAYS_TO_EXPIRATION,
    OC.NUMBER_OF_CONTRACTS,
    OC.ASSET_MAIN_TYPE,
    OC.ASSET_SUB_TYPE,
    OC.IS_CHAIN_TRUNCATED,
    
    OCED.EXP_DATE_MAP,
    OCED.EXP_DATE_PRICE_MAP, 
    
    OCED.PUT_CALL,
    OCED.SYMBOL_EXP_DATE,
    OCED.DESCRIPTION,
    OCED.EXCHANGE_NAME,
    OCED.BID,
    OCED.ASK,
    OCED.LAST,
    OCED.MARK,
    OCED.BID_SIZE,
    OCED.ASK_SIZE,
    OCED.BID_ASK_SIZE,
    OCED.LAST_SIZE,
    OCED.HIGH_PRICE,
    OCED.LOW_PRICE,
    OCED.OPEN_PRICE,
    OCED.CLOSE_PRICE,
    OCED.TOTAL_VOLUME,
    OCED.TRADE_TIME_IN_LONG,
    OCED.QUOTE_TIME_IN_LONG,
    OCED.NET_CHANGE,
    OCED.VOLATILIY,
    OCED.DELTA,
    OCED.GAMMA,
    OCED.THETA,
    OCED.VEGA,
    OCED.RHO,
    OCED.OPEN_INTEREST,
    OCED.TIME_VALUE,
    OCED.THEORETICAL_OPTION_VALUE,
    OCED.THEORETICAL_VOLATILITY,
    OCED.OPTION_DELIVERABLE_SYMBOL,
    OCED.OPTION_DELIVERABLE_ASSET_TYPE,
    OCED.OPTION_DELIVERABLE_UNITS,
    OCED.STRIKE_PRICE,
    OCED.EXPIRATION_DATE,
    OCED.DAYS_TO_EXPIRATION,
    OCED.EXPIRATION_TYPE,
    OCED.LAST_TRADING_DAY,
    OCED.MULTIPLIER,
    OCED.SETTLEMENT_TYPE,
    OCED.DELIVERABLE_NOTE,
    OCED.PERCENTAGE_CHANGE,
    OCED.MARK_CHANGE,
    OCED.MARK_PERCENTAGE_CHANGE,
    OCED.INTRINSIC_VALUE,
    OCED.EXTRINSIC_VALUE,
    OCED.OPTION_ROOT,
    OCED.EXERCISE_TYPE,
    OCED.HIGH_52_WEEK,
    OCED.LOW_52_WEEK,
    OCED.NON_STANDARD,
    OCED.PENNY_PILOT,
    OCED.IN_THE_MONEY,
    OCED.MINI
FROM
	OPTION_CHAIN OC,
    OPTION_CHAIN_PUT_EXP_DATE_MAP OCED
WHERE
	OC.SYMBOL      = OCED.SYMBOL AND
    OC.RECORD_DATE = OCED.RECORD_DATE;


SELECT * FROM OPTION_CHAIN_VIEW;

SELECT COUNT(*) FROM OPTION_CHAIN_VIEW; # 34,570 rows as of 6/23/2024

SELECT * FROM POSITION_VIEW;
