CREATE OR REPLACE VIEW POSITION_VIEW AS
SELECT 
    SYMBOL,
	RECORD_DATE,      
    STATUS,
    STRATEGY,
    INTERVAL_VALUE,
    IS_DELAYED BOOLEAN,
    IS_INDEX BOOLEAN,
    INTEREST_RATE DECIMAL(12, 4),
    UNDERLYING_PRICE DECIMAL(12, 4),
    VOLATILITY DECIMAL(12, 4),
    DAYS_TO_EXPIRATION DECIMAL(12, 4),
    NUMBER_OF_CONTRACTS INT,
    ASSET_MAIN_TYPE VARCHAR(100),
    ASSET_SUB_TYPE VARCHAR(100),
    IS_CHAIN_TRUNCATED BOOLEAN
FROM
	OPTION_CHAIN OC
