use financedb;

CREATE TABLE OPTION_CHAIN (
    SYMBOL VARCHAR(100) NOT NULL,
	RECORD_DATE DATETIME,  
    
    STATUS VARCHAR(100),
    STRATEGY VARCHAR(100),
    INTERVAL_VALUE DECIMAL(12, 4),
    IS_DELAYED BOOLEAN,
    IS_INDEX BOOLEAN,
    INTEREST_RATE DECIMAL(12, 4),
    UNDERLYING_PRICE DECIMAL(12, 4),
    VOLATILITY DECIMAL(12, 4),
    DAYS_TO_EXPIRATION DECIMAL(12, 4),
    NUMBER_OF_CONTRACTS INT,
    ASSET_MAIN_TYPE VARCHAR(100),
    ASSET_SUB_TYPE VARCHAR(100),
    IS_CHAIN_TRUNCATED BOOLEAN,
    PRIMARY KEY (SYMBOL, RECORD_DATE)
);

CREATE INDEX IDX_OPTION_CHAIN_SYMBOL
ON OPTION_CHAIN (SYMBOL);


CREATE INDEX IDX_OPTION_CHAIN_RECORD_DATE
ON OPTION_CHAIN (RECORD_DATE);


ALTER TABLE OPTION_CHAIN
MODIFY RECORD_DATE DATETIME;

#DELETE from OPTION_CHAIN WHERE DATE(RECORD_DATE) = '2024-06-25'; 
#COMMIT;

SELECT 
	SYMBOL,
    RECORD_DATE,
    COUNT(*) 
FROM 
	OPTION_CHAIN
GROUP BY SYMBOL, RECORD_DATE;