use financedb;

SELECT * FROM POSITION_VIEW;

/*
 * Select all relevant columns for analysis
 */
SELECT
	RECORD_DATE,
	ACCOUNT_DESCRIPTION,
	AVERAGE_PRICE,
    SHORT_QUANTITY,
	LONG_QUANTITY,
    ASSET_TYPE,
    SYMBOL, 
    UNDERLYING_SYMBOL,
    POSITION_DESCRIPTION,
    NET_CHANGE,
    PUT_CALL,
    MARKET_VALUE,
    MAINTENANCE_REQUIREMENT,
    AVERAGE_SHORT_PRICE,
    AVERAGE_LONG_PRICE,
    OPEN_INTEREST,
    DAYS_TO_EXPIRATION,
    THEORETICAL_VOLATILITY,
    VOLATILIY,
    DELTA,
    GAMMA,
    THETA,
    RHO,
    VEGA
FROM 
	POSITION_VIEW
WHERE
	ASSET_TYPE = 'OPTION'
ORDER BY 
	DAYS_TO_EXPIRATION;
    

/*
 * Stocks and ETF positions
 * NOTE: For stock and ETF position the AVERAGE_LONG_PRICE is the Trade Price
 */
SELECT
	RECORD_DATE,
	ACCOUNT_DESCRIPTION,
	AVERAGE_PRICE,
    SHORT_QUANTITY,
	LONG_QUANTITY,
    ASSET_TYPE,
    SYMBOL, 
    UNDERLYING_SYMBOL,
    POSITION_DESCRIPTION,
    NET_CHANGE,
    PUT_CALL,
    MARKET_VALUE,
    MAINTENANCE_REQUIREMENT,
    AVERAGE_SHORT_PRICE,
    AVERAGE_LONG_PRICE,
    OPEN_INTEREST,
    DAYS_TO_EXPIRATION,
    THEORETICAL_VOLATILITY,
    VOLATILIY,
    DELTA,
    GAMMA,
    THETA,
    RHO,
    VEGA
FROM 
	POSITION_VIEW
WHERE
	ASSET_TYPE <> 'OPTION'
ORDER BY 
	DAYS_TO_EXPIRATION;