CREATE TABLE ORDERS (
    ACCOUNT_NUMBER VARCHAR(100) NOT NULL,
    ORDER_ID VARCHAR(100),
    SESSION VARCHAR(100),
    DURATION VARCHAR(100),
    ORDER_TYPE VARCHAR(100),
    CANCEL_TIME DATETIME,
	COMPLEX_ORDDER_STRATEGY_TYPE VARCHAR(100),
    QUANTITY DECIMAL(12, 4),
    FILE_QUANTITY DECIMAL(12, 4),
    REMAINING_QUANTITY DECIMAL(12, 4),
    REQUEST_DESTINATION VARCHAR(100),
    DESTINATION_LINK_NAME VARCHAR(100),
    PRICE DECIMAL(12, 4),
    ORDER_STRATEGY_TYPE VARCHAR(100),
    CANCELLABLE BOOLEAN,
    EDITABLE BOOLEAN,
    STATUS VARCHAR(100),
    ENTERED_TIME DATETIME,
    CLOSE_TIME DATETIME,
    TAG VARCHAR(100),
    PRIMARY KEY (ACCOUNT_NUMBER, ORDER_ID)
 );
 
 
 /*
  * ORDER Queries
  * ORDER + ORDER_LEG_COLLECTION + OPTION_DELIVERABLE + ORDER_ACTIVITY_COLLECTION + EXECUTION_LEGS
  */
  
 SELECT * FROM ORDERS ORDER BY ENTERED_TIME DESC;
 
 SELECT * FROM ORDERS ORDER BY CLOSE_TIME DESC;
 
 SELECT ACCOUNT_NUMBER, STATUS, COUNT(*) as TOTAL FROM ORDERS 
 GROUP BY ACCOUNT_NUMBER, STATUS;
 
 SELECT * FROM ORDERS WHERE ORDER_ID = '1000522597455';
 
 