CREATE TABLE ORDER_LEG_COLLECTION (
    ACCOUNT_NUMBER VARCHAR(100) NOT NULL,
	ORDER_ID VARCHAR(100),
    LEG_ID INT,
    ORDER_LEG_TYPE VARCHAR(100),
    INSTRUMENT_ASSET_TYPE VARCHAR(100),
    INSTRUMENT_CUSIP VARCHAR(100),
    INSTRUMENT_SYMBOL VARCHAR(100),
    INSTRUMENT_DESCRIPTION VARCHAR(100),
    INSTRUMENT_ID VARCHAR(100),
    INSTRUMENT_TYPE VARCHAR(100),
    INSTRUMENT_PUT_CALL VARCHAR(100),
    INSTRUMENT_UNDERLYING_SYMBOL VARCHAR(100),
    INSTRUCTION VARCHAR(100),
    POSITION_EFFECT VARCHAR(100),
    QUANTITY DECIMAL(12, 4),
    PRIMARY KEY (ACCOUNT_NUMBER, ORDER_ID, LEG_ID)
);

SELECT * FROM ORDER_LEG_COLLECTION;