CREATE TABLE ORDERS (
    ACCOUNT_NUMBER VARCHAR(100) NOT NULL,
    RECORD_DATE DATE,
    SESSION VARCHAR(100),
    DURATION VARCHAR(100),
    ORDER_TYPE VARCHAR(100),
    CANCEL_TIME DATETIME,
	COMPLEX_ORDDER_STRATEGY_TYPE VARCHAR(100),
    QUANTITY DECIMAL(12, 4),
    FILE_QUANTITY DECIMAL(12, 4),
    REMAINING_QUANTITY DECIMAL(12, 4),
    REQUEST_DESTINATION VARCHAR(100),
    DESTINATION_LINK_NAME VARCHAR(100),
    PRICE DECIMAL(12, 4),
    
    ORDER_STRATEGY_TYPE VARCHAR(100),
    ORDER_ID VARCHAR(100),
    CANCELLABLE BOOLEAN,
    EDITABLE BOOLEAN,
    STATUS VARCHAR(100),
    ENTERED_TIME DATETIME,
    TAG VARCHAR(100),
    PRIMARY KEY (ACCOUNT_NUMBER, RECORD_DATE, ORDER_ID)
 );