CREATE TABLE ORDER_ACTIVITY_COLLECTION (
    ACCOUNT_NUMBER VARCHAR(100) NOT NULL,
    RECORD_DATE DATE,
	ORDER_ID VARCHAR(100),    
    ACTIVITY_ID VARCHAR(100),
    ACTIVITY_TYPE VARCHAR(100),
    EXECUTION_TYPE VARCHAR(100),
    QUANTITY DECIMAL(12, 4),
    OREDER_REMAINING_QUANTITY DECIMAL(12, 4),
    PRIMARY KEY (ACCOUNT_NUMBER, RECORD_DATE, ORDER_ID, ACTIVITY_ID)
);