use financedb;

/*
 * POSITION + INITIAL_BALANCE + CURRENT_BALANCE + PROJECTED_BALANCE 
 */
SELECT * FROM POSITION_VIEW;

/*
 * Select all relevant columns for analysis
 */
SELECT
	RECORD_DATE,
	ACCOUNT_DESCRIPTION,
	AVERAGE_PRICE,
    SHORT_QUANTITY,
	LONG_QUANTITY,
    ASSET_TYPE,
    SYMBOL, 
    POSITION_DESCRIPTION,
    NET_CHANGE,
    PUT_CALL,
    MARKET_VALUE,
    MAINTENANCE_REQUIREMENT,
    AVERAGE_SHORT_PRICE,
    AVERAGE_LONG_PRICE,
    OPEN_INTEREST,
    DAYS_TO_EXPIRATION,
    THEORETICAL_VOLATILITY,
    VOLATILIY,
    DELTA,
    GAMMA,
    THETA,
    RHO,
    VEGA
FROM 
	POSITION_VIEW
ORDER BY 
	DAYS_TO_EXPIRATION;
    
    
    
SELECT
	RECORD_DATE,
	ACCOUNT_DESCRIPTION,
	AVERAGE_PRICE,
    SHORT_QUANTITY,
	LONG_QUANTITY,
    ASSET_TYPE,
    SYMBOL, 
    POSITION_DESCRIPTION,
    NET_CHANGE,
    PUT_CALL,
    MARKET_VALUE,
    MAINTENANCE_REQUIREMENT,
    AVERAGE_SHORT_PRICE,
    AVERAGE_LONG_PRICE,
    OPEN_INTEREST,
    DAYS_TO_EXPIRATION,
    VOLATILIY,
    DELTA,
    GAMMA,
    THETA,
    RHO,
    VEGA
FROM 
	POSITION_VIEW
WHERE
	ASSET_TYPE = 'OPTION' AND
    DELTA > .1
ORDER BY 
	DAYS_TO_EXPIRATION;
    
    
SELECT * FROM OPTION_CHAIN_EXP_DATE_MAP where SYMBOL_EXP_DATE = 'SPXW  240723P05100000';

SELECT * FROM OPTION_CHAIN_EXP_DATE_MAP where SYMBOL_EXP_DATE = 'QQQ   241018C00495000';

SELECT * FROM OPTION_CHAIN_EXP_DATE_MAP where SYMBOL_EXP_DATE = 'TSLA  241011C00250000';




