use financedb;

SELECT count(*) FROM POSITION_VIEW;

SELECT * FROM POSITION_VIEW;

/*
 * Select all relevant columns for analysis
 */
SELECT
	RECORD_DATE,
	ACCOUNT_DESCRIPTION,
	AVERAGE_PRICE,
    SHORT_QUANTITY,
	LONG_QUANTITY,
    ASSET_TYPE,
    SYMBOL, 
    POSITION_DESCRIPTION,
    NET_CHANGE,
    PUT_CALL,
    MARKET_VALUE,
    MAINTENANCE_REQUIREMENT,
    AVERAGE_SHORT_PRICE,
    AVERAGE_LONG_PRICE,
    OPEN_INTEREST,
    DAYS_TO_EXPIRATION,
    THEORETICAL_VOLATILITY,
    VOLATILIY,
    DELTA,
    GAMMA,
    THETA,
    RHO,
    VEGA
FROM 
	POSITION_VIEW
ORDER BY 
	DAYS_TO_EXPIRATION;
    
    
    
SELECT
	RECORD_DATE,
	ACCOUNT_DESCRIPTION,
	AVERAGE_PRICE,
    SHORT_QUANTITY,
	LONG_QUANTITY,
    ASSET_TYPE,
    SYMBOL, 
    POSITION_DESCRIPTION,
    NET_CHANGE,
    PUT_CALL,
    MARKET_VALUE,
    MAINTENANCE_REQUIREMENT,
    AVERAGE_SHORT_PRICE,
    AVERAGE_LONG_PRICE,
    OPEN_INTEREST,
    DAYS_TO_EXPIRATION,
    THEORETICAL_VOLATILITY,
    VOLATILIY,
    DELTA,
    GAMMA,
    THETA,
    RHO,
    VEGA
FROM 
	POSITION_VIEW
WHERE
	ASSET_TYPE = 'OPTION'
ORDER BY 
	DAYS_TO_EXPIRATION;
    
/*
 * pie_chart query
 */
SELECT 
	AR.ACCOUNT_DESCRIPTION,
	DB.ACCOUNT_NUMBER,
	DB.RECORD_DATE,
	DB.LIQUIDITY_VALUE
FROM 
	DAILY_BALANCE DB,
	ACCOUNT_REFERENCE AR
WHERE
	DB.ACCOUNT_NUMBER = AR.ACCOUNT_NUMBER AND
	DATE(RECORD_DATE) = (SELECT MAX(RECORD_DATE) FROM DAILY_BALANCE);
     
/*
 * option_position_piechart
 */
SELECT 
	UNDERLYING_SYMBOL,
	SUM(MAINTENANCE_REQUIREMENT) AS MAINTENANCE_REQUIREMENT
FROM 
	POSITION_VIEW
WHERE 
	ASSET_TYPE = 'OPTION' AND
	DATE(RECORD_DATE) = (SELECT MAX(RECORD_DATE) FROM POSITION)
GROUP BY
	UNDERLYING_SYMBOL;

/*
 * Number of option positions for each item in the Watch List
 * even if there is no position in the POSITION_VIEW
 */
SELECT 
    B.SYMBOL,
    COUNT(B.SYMBOL)
FROM
    WATCH_LIST B
    LEFT JOIN POSITION_VIEW A ON B.SYMBOL = A.UNDERLYING_SYMBOL
        AND A.ASSET_TYPE = 'OPTION'
        AND DATE(A.RECORD_DATE) = (SELECT MAX(RECORD_DATE) FROM POSITION)
GROUP BY
    B.SYMBOL;

/*
 * If you want to include all symbols from the POSITION_VIEW table instead, you can use a RIGHT JOIN:
 */
SELECT 
    B.SYMBOL,
    COUNT(B.SYMBOL)
FROM
    WATCH_LIST B
    RIGHT JOIN POSITION_VIEW A ON B.SYMBOL = A.UNDERLYING_SYMBOL
        AND A.ASSET_TYPE = 'OPTION'
        AND DATE(A.RECORD_DATE) = (SELECT MAX(RECORD_DATE) FROM POSITION)
GROUP BY
    B.SYMBOL;

