CREATE VIEW POSITION_VIEW AS
SELECT
	A.ACCOUNT_NUMBER,
    A.HASH_VALUE,
    A.TYPE AS ACCOUNT_TYPE,
    A.ROUND_TRIPS,
    A.IS_DAY_TRADER,
    A.IS_CLOSING_ONLY_RESTRICTED,
    A.PFCB_FLAG,
    P.SHORT_QUANTITY,
	P.AVERAGE_PRICE,
    P.CURRENT_DAY_PROFIT_LOSS,
    P.CURRENT_DAY_PROFIT_LOSS_PERCENTAGE,
    P.LONG_QUANTITY,
    P.SETTLED_LONG_QUANTITY,
    P.SETTLED_SHORT_QUANTITY,
    P.ASSET_TYPE,
    P.CUSIP,
    P.SYMBOL,
    P.POSITION_DESCRIPTION,
    P.NET_CHANGE,
    P.POSITION_INSTRUMENT_TYPE,
    P.PUT_CALL,
    P.UNDERLYING_SYMBOL,
    P.MARKET_VALUE,
    P.MAINTENANCE_REQUIREMENT,
    P.AVERAGE_SHORT_PRICE,
    P.TAX_LOT_AVERAGE_SHORT_PRICE,
    P.SHORT_OPEN_PROFIT_LOSS,
    P.PREVIOUS_SESSION_SHORT_QUANTITY,
    P.AVERAGE_LONG_PRICE,
    P.TAX_LOT_AVERAGE_LONG_PRICE,
    P.LONG_OPEN_PROFIT_LOSS,
    P.PREVIOUS_SESSION_LONG_QUANTITY,
    P.CURRENT_DAY_COST
FROM
	ACCOUNT A,
    POSITION P
WHERE
	A.ACCOUNT_NUMBER = P.ACCOUNT_NUMBER;


/* 
 * QUERY FOR POSITION_VIEW
 */ 
select * from POSITION_VIEW;

select count(*) from POSITION_VIEW;