CREATE OR REPLACE VIEW POSITION_VIEW_TEST AS
SELECT
    P.ACCOUNT_NUMBER,
    P.RECORD_DATE,
    P.SHORT_QUANTITY,
    P.AVERAGE_PRICE,
    P.CURRENT_DAY_PROFIT_LOSS,
    P.CURRENT_DAY_PROFIT_LOSS_PERCENTAGE,
    P.LONG_QUANTITY,
    P.SETTLED_LONG_QUANTITY,
    P.SETTLED_SHORT_QUANTITY,
    P.ASSET_TYPE,
    P.CUSIP,
    P.SYMBOL,
    P.POSITION_DESCRIPTION,
    P.NET_CHANGE,
    P.POSITION_INSTRUMENT_TYPE,
    P.PUT_CALL,
    P.UNDERLYING_SYMBOL,
    P.MARKET_VALUE,
    P.MAINTENANCE_REQUIREMENT,
    P.AVERAGE_SHORT_PRICE,
    P.TAX_LOT_AVERAGE_SHORT_PRICE,
    P.SHORT_OPEN_PROFIT_LOSS,
    P.PREVIOUS_SESSION_SHORT_QUANTITY,
    P.AVERAGE_LONG_PRICE,
    P.TAX_LOT_AVERAGE_LONG_PRICE,
    P.LONG_OPEN_PROFIT_LOSS,
    P.PREVIOUS_SESSION_LONG_QUANTITY,
    P.CURRENT_DAY_COST,
    O.OPEN_INTEREST,
    O.DAYS_TO_EXPIRATION,
    O.THEORETICAL_VOLATILITY,
    O.VOLATILIY,
    O.DELTA,
    O.GAMMA,
    O.THETA,
    O.RHO,
    O.VEGA
FROM
    POSITION P
INNER JOIN OPTION_CHAIN_EXP_DATE_MAP O ON P.SYMBOL = O.SYMBOL_EXP_DATE
INNER JOIN (
    SELECT SYMBOL_EXP_DATE, MAX(RECORD_DATE) AS MAX_DATE
    FROM OPTION_CHAIN_EXP_DATE_MAP
    GROUP BY SYMBOL_EXP_DATE
) D ON O.SYMBOL_EXP_DATE = D.SYMBOL_EXP_DATE AND O.RECORD_DATE = D.MAX_DATE;

select * from POSITION_VIEW_TEST;
