use financedb;

select * from POSITION_VIEW;


select
	RECORD_DATE,
	ACCOUNT_DESCRIPTION,
	AVERAGE_PRICE,
    SHORT_QUANTITY,
	LONG_QUANTITY,
    ASSET_TYPE,
    SYMBOL, 
    POSITION_DESCRIPTION,
    NET_CHANGE,
    PUT_CALL,
    MARKET_VALUE,
    MAINTENANCE_REQUIREMENT,
    AVERAGE_SHORT_PRICE,
    AVERAGE_LONG_PRICE,
    OPEN_INTEREST,
    DAYS_TO_EXPIRATION,
    THEORETICAL_VOLATILITY,
    VOLATILIY,
    DELTA,
    GAMMA,
    THETA,
    RHO,
    VEGA
from 
	POSITION_VIEW;