CREATE TABLE PROJECTED_BALANCE (
    ACCOUNT_NUMBER VARCHAR(100) NOT NULL,
    RECORD_DATE DATE,
	AVAILABLE_FUNDS DECIMAL(12, 4),
    AVAILABLE_FUNDS_NON_MARGINABLE_TRADE DECIMAL(12, 4),
    BUYING_POWER DECIMAL(12, 4),
    DAY_TRADING_BUYING_POWER DECIMAL(12, 4),
    DAY_TRADING_BUYING_POWER_CALL DECIMAL(12, 4),
    MAINTENANCE_CALL DECIMAL(12, 4),
    REG_T_CALL DECIMAL(12, 4),
    IS_IN_CALL BOOLEAN,
    STOCK_BUYING_POWER DECIMAL(12, 4),
    PRIMARY KEY (ACCOUNT_NUMBER, RECORD_DATE)
);

SELECT * FROM PROJECTED_BALANCE;