use financedb;

CREATE TABLE TRANSFER_ITEM_OPTION_DELIVERABLE (
	ACTIVITY_ID VARCHAR(100) NOT NULL, # Link to TRANSACTIONS table
    
    ROOT_SYMBOL VARCHAR(100) NOT NULL,
    STRIKE_PERCENT INT,
    DELIVERABLE_NUMBER INT,
    DELIVERABLE_UNITS DECIMAL(12, 4),
    
    DELIVERABLE_ASSET_TYPE VARCHAR(100),
    DELIVERABLE_STATUS VARCHAR(100),
    DELIVERABLE_SYMBOL VARCHAR(100),
    DELIVERABLE_DESCRIPTION VARCHAR(100),
    DELIVERABLE_INSTRUMENT_ID VARCHAR(100),
    DELIVERABLE_CLOSING_PRICES DECIMAL(12, 4),
    DELIVERABLE_TYPE VARCHAR(100)
);
