use financedb;

CREATE TABLE TRANSFER_ITEM (
	ACCOUNT_NUMBER VARCHAR(100) NOT NULL,
    ACTIVITY_ID VARCHAR(100) NOT NULL,
    
    INSTRUMENT_ASSSET_TYPE VARCHAR(100) NOT NULL,
    INSTRUMENT_STATUS VARCHAR(100) NOT NULL,
    INSTRUMENT_SYMBOL VARCHAR(100) NOT NULL,
    INSTRUMENT_DESCRIPTION VARCHAR(100) NOT NULL,
    INSTRUMENT_ID VARCHAR(100) NOT NULL,
    INSTRUMENT_CLOSING_PRICE DECIMAL(12, 4),
    
	RECORD_TIME DATETIME,    
    ACCOUNT_NUMBER VARCHAR(100),
    TYPE VARCHAR(100),
    STATUS VARCHAR(100),
    SUB_ACCOUNT VARCHAR(100),
    TRADE_DATE DATETIME,
    ORDER_ID VARCHAR(100),
    NET_AMOUNT DECIMAL(12, 4),
    FOREIGN KEY (ACCOUNT_NUMBER, ACTIVITY_ID) REFERENCES TRANSACTIONS(ACCOUNT_NUMBER, ACTIVITY_ID)
);
