CREATE TABLE TRANSACTIONS_OPTION_DELIVERABLE (
    ACCOUNT_NUMBER VARCHAR(100) NOT NULL,
    ACTIVITY_ID VARCHAR(100) NOT NULL,
	ROOT_SYMBOL VARCHAR(100),    
    STRIKE_PERCENT INT,
    DELIVERABLE_NUMBER INT,
    DELIVERABLE_UNITS DECIMAL(12, 4),
    FOREIGN KEY (ACCOUNT_NUMBER, ACTIVITY_ID) REFERENCES TRANSACTIONS(ACCOUNT_NUMBER, ACTIVITY_ID)
);
