use financedb;

CREATE TABLE TRANSACTIONS (
    ACTIVITY_ID VARCHAR(100) NOT NULL,
	RECORD_TIME DATETIME,    
    ACCOUNT_NUMBER VARCHAR(100),
    TYPE VARCHAR(100),
    STATUS VARCHAR(100),
    SUB_ACCOUNT VARCHAR(100),
    TRADE_DATE DATETIME,
    ORDER_ID VARCHAR(100),
    NET_AMOUNT DECIMAL(12, 4),
    PRIMARY KEY (ACCOUNT_NUMBER, ACTIVITY_ID, ORDER_ID)
);
