use financedb;

RENAME TABLE TRANSACTIONS_OLD TO TRANSACTIONS;

DESC TRANSACTIONS_OLD;

CREATE TABLE TRANSACTIONS (
    ACTIVITY_ID VARCHAR(100) NOT NULL,
    RECORD_TIME DATETIME, 
    DESCRIPTION VARCHAR(100),
    ACCOUNT_NUMBER VARCHAR(100),
    TYPE VARCHAR(100),
    STATUS VARCHAR(100),
    SUB_ACCOUNT VARCHAR(100),
    TRADE_DATE DATETIME,
    POSITION_ID VARCHAR(100),
    SETTLEMENT_DATE DATETIME,
    ORDER_ID VARCHAR(100),
    NET_AMOUNT DECIMAL(12, 4),
    PRIMARY KEY (ACCOUNT_NUMBER, ACTIVITY_ID)
);

SELECT * FROM TRANSACTIONS;

SELECT COUNT(*) FROM TRANSACTIONS; # 897 as of 622

SELECT COUNT(DISTINCT(ACTIVITY_ID)) FROM TRANSACTIONS;

SELECT ACTIVITY_ID, COUNT(ACTIVITY_ID) FROM TRANSACTIONS GROUP BY ACTIVITY_ID;



SELECT
    COUNT(TI.ACTIVITY_ID)
FROM
	TRANSFER_ITEM TI,
	TRANSACTIONS T,
    TRANSFER_ITEM_OPTION_DELIVERABLE TIOD
WHERE
	TI.ACTIVITY_ID = T.ACTIVITY_ID AND
    TI.ACTIVITY_ID = TIOD.ACTIVITY_ID;

SELECT * FROM TRANSACTIONS_VIEW
ORDER BY RECORD_TIME DESC;

/*
 * Display all transactions in descending order
 * TRANSITION + TRANSFER_ITEM + TRANSFER_ITEM_OPTION_DELIVERABLE
 */
SELECT * FROM TRANSACTIONS ORDER BY RECORD_TIME DESC;

SELECT * FROM TRANSACTIONS_VIEW ORDER BY RECORD_TIME DESC;

/*
 * What are the distinct POSITION_EFFECTs?
 * Answer: OPENING and CLOSING + null
 */
SELECT DISTINCT(POSITION_EFFECT) FROM TRANSACTIONS_VIEW;

SELECT 
	POSITION_EFFECT,
    COUNT(POSITION_EFFECT)
FROM 
	TRANSACTIONS_VIEW
GROUP BY
	POSITION_EFFECT;

