CREATE TABLE TRANSACTIONS_OPTION_DELIVERABLE (
    ACCOUNT_NUMBER VARCHAR(100) NOT NULL,
	ORDER_ID VARCHAR(100),    
    LEG_ID INT,
    SYMBOL VARCHAR(100),
    DELIVERABLE_UNITS DECIMAL(12, 4),
    PRIMARY KEY (ACCOUNT_NUMBER, ORDER_ID, LEG_ID)
);

SELECT * FROM OPTION_DELIVERABLE;