use financedb;

CREATE TABLE TRANSACTIONS (
    ACTIVITY_ID VARCHAR(100) NOT NULL,
	RECORD_TIME DATETIME,  
    DESCRIPTION VARCHAR(100),
    ACCOUNT_NUMBER VARCHAR(100),
    TYPE VARCHAR(100),
    STATUS VARCHAR(100),
    SUB_ACCOUNT VARCHAR(100),
    TRADE_DATE DATETIME,
    POSITION_ID VARCHAR(100),
    SETTLEMENT_DATE DATETIME,
    ORDER_ID VARCHAR(100),
    NET_AMOUNT DECIMAL(12, 4),
    PRIMARY KEY (ACCOUNT_NUMBER, ACTIVITY_ID)
);

SELECT * FROM TRANSACTIONS;

SELECT COUNT(*) FROM TRANSACTIONS; # 897 as of 622

SELECT COUNT(DISTINCT(ACTIVITY_ID)) FROM TRANSACTIONS;

SELECT ACTIVITY_ID, COUNT(ACTIVITY_ID) FROM TRANSACTIONS GROUP BY ACTIVITY_ID;


SELECT * FROM TRANSACTIONS ORDER BY RECORD_TIME DESC;

SELECT
	T.*,
    TI.*,
    TIOD.*
FROM 
	TRANSACTIONS T,
	TRANSFER_ITEM TI,
    TRANSFER_ITEM_OPTION_DELIVERABLE TIOD
WHERE
	T.ACTIVITY_ID = TI.ACTIVITY_ID AND
    TI.ACTIVITY_ID = TIOD.ACTIVITY_ID;

