use financedb;

CREATE TABLE TRANSFER_ITEM (
	ACTIVITY_ID VARCHAR(100) NOT NULL, # Link to TRANSACTIONS table
    INSTRUMENT_ASSSET_TYPE VARCHAR(100) NOT NULL,
    INSTRUMENT_STATUS VARCHAR(100) NOT NULL,
    INSTRUMENT_SYMBOL VARCHAR(100) NOT NULL,
    INSTRUMENT_DESCRIPTION VARCHAR(100), # May not always be available
    INSTRUMENT_ID VARCHAR(100) NOT NULL,
    INSTRUMENT_EXPIRATION_DATE DATETIME, # May not always be available
    INSTRUMENT_CLOSING_PRICE DECIMAL(12, 4), # May not always be available
    
    INSTRUMENT_OPTION_PREMIUM_MULTIPLIER INT,
    INSTRUMENT_PUT_CALL VARCHAR(100),
    INSTRUMENT_STRIKE_PRICE DECIMAL(12, 4),
    INSTRUMENT_TYPE VARCHAR(100),
    INSTRUMENT_UNDERLYING_SYMBOL VARCHAR(100),
    INSTRUMENT_UNDERLYING_CUSIP VARCHAR(100),
    
    AMOUNT DECIMAL(12, 4), # May not always be available
    COST DECIMAL(12, 4), # May not always be available
    FEE_TYPE VARCHAR(100), # May not always be available    
    PRICE DECIMAL(12, 4), # May not always be available
    POSITION_EFFECT VARCHAR(100), # May not always be available
    PRIMARY KEY (ACTIVITY_ID, INSTRUMENT_ASSSET_TYPE, INSTRUMENT_SYMBOL, FEE_TYPE)
);

SELECT * FROM TRANSFER_ITEM;

SELECT COUNT(*) FROM TRANSFER_ITEM; # 4178

SELECT COUNT(DISTINCT(ACTIVITY_ID)) FROM TRANSFER_ITEM; # 897


SELECT * FROM TRANSFER_ITEM WHERE ACTIVITY_ID IN (
SELECT T.ACTIVITY_ID
FROM TRANSFER_ITEM T
LEFT JOIN TRANSFER_ITEM_OPTION_DELIVERABLE D ON T.ACTIVITY_ID = D.ACTIVITY_ID
WHERE D.ACTIVITY_ID IS NULL);
