use financedb;

CREATE TABLE TRANSFER_ITEM_OPTION_DELIVERABLE (
	ACTIVITY_ID VARCHAR(100) NOT NULL, # Link to TRANSACTIONS table
    
    ROOT_SYMBOL VARCHAR(100) NOT NULL,
    STRIKE_PERCENT INT,
    DELIVERABLE_NUMBER INT,
    DELIVERABLE_UNITS DECIMAL(12, 4),
    
    DELIVERABLE_ASSET_TYPE VARCHAR(100),
    DELIVERABLE_STATUS VARCHAR(100),
    DELIVERABLE_SYMBOL VARCHAR(100),
    DELIVERABLE_DESCRIPTION VARCHAR(100),
    DELIVERABLE_INSTRUMENT_ID VARCHAR(100),
    DELIVERABLE_CLOSING_PRICES DECIMAL(12, 4),
    DELIVERABLE_TYPE VARCHAR(100),
    PRIMARY KEY (ACTIVITY_ID)
);


SELECT * FROM TRANSFER_ITEM_OPTION_DELIVERABLE;

SELECT COUNT(ACTIVITY_ID) FROM TRANSFER_ITEM_OPTION_DELIVERABLE; # 889 as of 6/22/2024

SELECT COUNT(DISTINCT(ACTIVITY_ID)) FROM TRANSFER_ITEM_OPTION_DELIVERABLE; # 889 as of 6/22/2024

# Which TRANSFER_ITEM DOES NOT HAVE A TRANSFER_ITEM_OPTION_DELIVERABLE
SELECT T.ACTIVITY_ID
FROM TRANSFER_ITEM T
LEFT JOIN TRANSFER_ITEM_OPTION_DELIVERABLE D ON T.ACTIVITY_ID = D.ACTIVITY_ID
WHERE D.ACTIVITY_ID IS NULL;


