use financedb;

CREATE TABLE WATCH_LIST (
    SYMBOL VARCHAR(100) NOT NULL,
    YFINANCE_SYMBOL VARCHAR(100),
    GOOGLE_NEWS_SYMBOL VARCHAR(100),
	NAME VARCHAR(100),
    PRIMARY KEY (SYMBOL)
);



INSERT INTO WATCH_LIST (SYMBOL, YFINANCE_SYMBOL, GOOGLE_NEWS_SYMBOL, NAME)
VALUES ('GLD', 'GLD', 'SPDR Gold Shares (GLD)', 'SPDR Gold Shares');

COMMIT;


DELETE FROM WATCH_LIST WHERE SYMBOL = 'CAT';

ROLLBACK;


UPDATE WATCH_LIST
SET 
GOOGLE_NEWS_SYMBOL = 'Tesla, Inc. (TSLA)',
NAME = 'Tesla, Inc.'
WHERE SYMBOL = 'TSLA';


SET SQL_SAFE_UPDATES = 0; # DISABLE SAFE UPDATE 

UPDATE WATCH_LIST
SET 
SYMBOL = '$SPX'
WHERE YFINANCE_SYMBOL = '^SPX';

COMMIT;

SELECT GOOGLE_NEWS_SYMBOL FROM WATCH_LIST ORDER BY SYMBOL;

SELECT SYMBOL, GOOGLE_NEWS_SYMBOL FROM WATCH_LIST ORDER BY SYMBOL;

SELECT * FROM WATCH_LIST WHERE SYMBOL <> 'SPX' ORDER BY SYMBOL;

SELECT * FROM WATCH_LIST ORDER BY SYMBOL;
